on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: sizer_cli.bin
            asset_name: sizer-linux
          - os: windows-latest
            artifact_name: sizer_cli.exe
            asset_name: sizer-windows.exe
          - os: macos-latest
            artifact_name: sizer_cli.bin
            asset_name: sizer-macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@v1.4
        with:
          nuitka-version: 2.7
          script-name: sizer_cli.py
          mode: onefile

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
